        # Import all models to ensure they are registered with SQLModel
from .user import (
    User,
    OAuthAccount,
    Profile,
    Education,
    Skill,
    Interest,
    Availability,
    StudyPreference,
    PortfolioItem,
    Match,
    MatchCandidate,
    MatchFeedback,
    ChatRoom,
    Message,
    StudySession,
    AnalyticsEvent,
    RefreshToken,
    EmailVerificationToken,
    PhoneOTP,
    PasswordResetToken,
    AIConversation
)

# This ensures all models are registered
__all__ = [
    "User",
    "OAuthAccount",
    "Profile",
    "Education",
    "Skill",
    "Interest",
    "Availability",
    "StudyPreference",
    "PortfolioItem",
    "Match",
    "MatchCandidate",
    "MatchFeedback",
    "ChatRoom",
    "Message",
    "StudySession",
    "AnalyticsEvent",
    "RefreshToken",
    "EmailVerificationToken",
    "PhoneOTP",
    "PasswordResetToken",
    "AIConversation",
]
